name: npm-runner
version: 1.0.0
icon: "npm.svg"

inputs:
- name: FLOWCI_GIT_REPO
  type: string
  required: true

- name: NODE_IMG_VERSION
  type: string
  value: "12"
  required: false

- name: NPM_CMD
  type: string
  required: true

- name: NPM_REPORT_PATH
  type: string
  required: false

docker:
  image: node:${NODE_IMG_VERSION}

script: |
  
  cnpm()
  {
    npm --registry=https://registry.npm.taobao.org \
    --cache=$HOME/.npm/.cache/cnpm \
    --disturl=https://npm.taobao.org/dist \
    --userconfig=$HOME/.cnpmrc "$@"
  }

  cd $FLOWCI_GIT_REPO

  [[ -d $(npm bin) ]] && export PATH=$(npm bin):$PATH
  ${NPM_CMD}

  if [[ -d $NPM_REPORT_PATH ]]; then
    echo $NPM_REPORT_PATH
    plugindir=${FLOWCI_AGENT_PLUGIN_DIR}/npm-runner
    python3 ${plugindir}/report.py $NPM_REPORT_PATH index.html
  fi