name: npm-runner
version: 1.0.0
icon: "npm.svg"

inputs:
- name: NPM_CMD
  type: string
  required: true

- name: NPM_REPORT_PATH
  type: string
  required: false

script: |
  
  npm config set cache ${FLOWCI_AGENT_WORKSPACE}/npm-cache --global 

  cnpm()
  {
    npm --registry=https://registry.npm.taobao.org \
    --cache=$FLOWCI_AGENT_WORKSPACE/.npm/.cache/cnpm \
    --disturl=https://npm.taobao.org/dist \
    --userconfig=$FLOWCI_AGENT_WORKSPACE/.cnpmrc "$@"
  }

  cd $FLOWCI_GIT_REPO
  [[ -d $(npm bin) ]] && export PATH=$(npm bin):$PATH
  ${NPM_CMD}

  if [[ -d $NPM_REPORT_PATH ]]; then
    echo $NPM_REPORT_PATH
    plugindir=${FLOWCI_AGENT_PLUGIN_DIR}/npm-runner
    python3 ${plugindir}/report.py $NPM_REPORT_PATH index.html
  fi