name: npm-runner
version: 1.0.0
icon: "npm.svg"

inputs:
- name: FLOWCI_GIT_REPO
  type: string
  required: true

- name: NODE_IMG_VERSION
  type: string
  value: "12"
  required: false

- name: NPM_CMD
  type: string
  required: true

- name: NPM_REPORT_PATH
  type: string
  required: false

- name: CNPM_ENABLE
  type: bool
  value: "false"
  required: false

docker:
  image: node:${NODE_IMG_VERSION}

script: |
  if [[ $CNPM_ENABLE == "true" ]]; then
    alias cnpm="npm --registry=https://registry.npm.taobao.org \
    --cache=$HOME/.npm/.cache/cnpm \
    --disturl=https://npm.taobao.org/dist \
    --userconfig=$HOME/.cnpmrc"
  fi

  cd $FLOWCI_GIT_REPO

  [[ -d $(npm bin) ]] && export PATH=$(npm bin):$PATH
  ${NPM_CMD}

  if [[ -z $NPM_REPORT_PATH ]]; then
    echo $NPM_REPORT_PATH
  fi